### PR TITLE
Reusable component (Image Component for light and Dark Mode)

### PR DESCRIPTION
**Pull request by Rimjhim20**
Hey @naufaldi  
Issue - #3
1.  I made folders for each component.
2.  Added reusable code for DarkImage Component 
3.  Added reusable code for LightImage Component
4. Imported it in page/index.js

Plz, check and merge my PR.
Thank You!

### CODE REVIEW

**Comment by naufaldi** [comment]
1.  Name folder components jus `button` or `DarkImage` , no need to add `component` name in each folder name
2. Add `Image` import in each Image Component NextJS. Because if not import will show error
image
3. Pls build in local first to make sure you Web Apps is not broke / error.

**Comment by Rimjhim20** [comment]
Okay, I'll make the necessary changes.

**Comment by Rimjhim20** [comment]
Hey! @naufaldi  plz check.

**Comment by naufaldi** [comment]
Nice!

**Pull request merged**
